//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceChecker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotmentRecord
    {
        public int RecordId { get; set; }
        public System.DateTime AllotmentDate { get; set; }
        public int CurrentAllotment { get; set; }
        public bool Acknowledged { get; set; }
        public int AllotmentRoomTypeId { get; set; }
    
        public virtual AllotmentRoomType AllotmentRoomType1 { get; set; }
    }
}
