//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceChecker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementLabel
    {
        public int LabelId { get; set; }
        public string LabelName { get; set; }
        public int ActionId { get; set; }
        public int ExpectedBehavior { get; set; }
        public int LabelOrder { get; set; }
        public string XPath { get; set; }
        public int WaitSeconds { get; set; }
        public int WaitType { get; set; }
        public int ExpectedResultType { get; set; }
        public string ResultXPath { get; set; }
        public bool SetCurrentElement { get; set; }
        public int OffX { get; set; }
        public int OffY { get; set; }
        public string CustomData { get; set; }
        public string InputDataKey { get; set; }
        public string ReturnDataKey { get; set; }
    
        public virtual WebAction WebAction { get; set; }
    }
}
