//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceChecker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.ContractRooms = new HashSet<ContractRoom>();
        }
    
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public bool IsDuplicated { get; set; }
        public string HMSID { get; set; }
        public bool CheckAllotment { get; set; }
        public int CityId { get; set; }
        public decimal StarRating { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ContractValidTo { get; set; }
        public System.DateTime ContractValidFrom { get; set; }
        public int MinCutOffDates { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoom> ContractRooms { get; set; }
    }
}
